### ISSUE TITLE
Your names not clear in Dashboard Footer, Also social media links are not clearly visible

### ISSUE THREAD

**Issue by Signior-X** [pranshukharkwal/7UP-7Down#11]
From everywhere, I can see in the footer, except in the dashboard. See,
![Screenshot from 2020-04-02 00-52-55](https://user-images.githubusercontent.com/56730716/78178093-b898a680-747c-11ea-8812-797b73b36fd6.png)

_See the footer.__

**Comment by pranshukharkwal** [comment]
Do you see this issue in pages other than the dashboard?

**Comment by Signior-X** [comment]
nope only in dashboard, either change the footer color or change the footer only for dashboard.
